### ISSUE TITLE
Undefined Variable: hasSendgrid on Setup->Integrations

### ISSUE THREAD

**Issue by justlevine** [codelight-eu/gdpr-framework#11]
On `wp-admin/index.php?page=gdpr-setup&gdpr-step=integrations` page, I'm getting a PHP Notice:
`Notice: Undefined variable: hasSendgrid in D:\www\thegsc\wp-content\plugins\gdpr-framework\views\installer\steps\integrations.php on line 27`

Seems to be a simple typo: gdpr-framework/src/Installer/Steps/Integrations.php line 26 declares the variable as $hasSend**G**rid (with a capital 'G') but the views/...integrations.php uses a lowercase 'g'.

Steps to Reproduce:
1. Install and activate plugin (with WP_DEBUG enabled)
2. Run Plugin Setup
3. Reach Integrations Step

![has_sendgrid](https://user-images.githubusercontent.com/29322304/40632703-7386b16a-62f2-11e8-9aa3-aca37c11b815.PNG)

**Comment by indrek-k** [comment]
PR merged. Thanks a ton!
