### ISSUE TITLE
Data subject not found on email of visitors

### ISSUE THREAD

**Issue by ghost** [codelight-eu/gdpr-framework#4]
Hi guys, thank you for the plugin.
I am having a problem with consent given by a visitors (not existing wp user).

The consent given appear correctly in the table wp_gdpr_consent but the data subject is not found when searched in the Data Subjects tab "Find data subject by email" form and also the privacy-tools page form return a mail saying that there are no data stored for that mail address.
(i have copy pasted the mail address from the 'email' field of the db tab to prevent typo)

**Comment by ghost** [comment]
I fixed adding the following filter:

`add_filter('gdpr/data-subject/data', function($data , $email){
    $dataSubject = gdpr('data-subject')->getByEmail($email);
    $consents = $dataSubject->getConsents();
    if(!empty($consents)){
        $data['consents'] = $consents;
    }
    return $data;
}, 5, 2);`

I added an key 'consents' containing the consents array. Probably is something that has to be in he core (cause without it the 'visitor' feature is not working) ?

**Comment by indrek-k** [comment]
Thanks for this! I've fixed the results in Data Subjects tab with today's updates (not in WP repo yet, just here). I'll add the gdpr/data-subjects/data filter as well tomorrow and then release v1.0.6 with this fixed.

Thanks again!

**Comment by indrek-k** [comment]
Fixed with v1.0.6!
