### ISSUE TITLE
[FEATURE REQ] Send a warning email when someone request data deletion

### ISSUE THREAD

**Issue by teolaz** [codelight-eu/gdpr-framework#6]
Hi there, 
i think there's a small problem in plugin flux....
Let's speak with examples... You have an actor (who make actions) and a notified user (user who is notified when the actor do something) : if you enable notifications of a new registered user in site or (in example with Gravity Forms) an entire sent form entry, mail client of the notified user will also store information about the user who created that notification.
So, if you don't warn when there's a data deletion request, mail client of the notified user will continue to store personal data of the actor. Not so correct, IMHO...
What you think?

**Comment by indrek-k** [comment]
You are absolutely correct. Deletion requests will be logged in an upcoming release anyway.
But right now - under Tools > Privacy > General, you'll be able to set the delete action to 'delete and notify' which does send out an email. Does this help?

**Comment by teolaz** [comment]
And that's why a programmer should never do law analysis. GDPR is freezing my head, and naturally i didn't realized there was the option you mentioned.
Sorry mate :( Thanks for spotting that!

**Comment by indrek-k** [comment]
No worries, I've felt the exact same feeling for the whole 2018!
