### ISSUE TITLE
Conflict with Thrive Architect page builder

### ISSUE THREAD

**Issue by Genyus** [codelight-eu/gdpr-framework#8]
I discovered an issue on our site with a 500 error being thrown when using the Privacy Tools shortcode on a page edited by Thrive — it works for anonymous users or when editing the page using the default editor.

Turns out to be triggered by Thrive loading the page content from the call to `$consentInfo = apply_filters('the_content', gdpr('options')->get('consent_info'));` (PrivacyToolsPageController:167), leading to the do_shortcode filter entering an infinite loop.

I was able to resolve it by temporarily disabling and then re-adding the Thrive filters before and after the "gdpr/frontend/privacy-tools-page/content" action runs, like so:

```
function disableThriveFilters() {
  if(defined('TVE_VERSION')) {
    remove_filter( 'the_content', 'tve_clean_wp_editor_content', -100 );
    remove_filter( 'the_content', 'tve_editor_content', 10 );
  }
}

function enableThriveFilters() {
  if(defined('TVE_VERSION')) {
    add_filter( 'the_content', 'tve_clean_wp_editor_content', -100 );
    add_filter( 'the_content', 'tve_editor_content', 10 );
  }
}

// Default action has priority 10. So we'll disable the conflicting filters before it runs and then re-enable them after
add_action('gdpr/frontend/privacy-tools-page/content', 'disableThriveFilters', 9);
add_action('gdpr/frontend/privacy-tools-page/content', 'enableThriveFilters', 11);
```
Hope that helps

**Comment by indrek-k** [comment]
Hi there!

Thanks so much for tracking this down!

So the problem is in nested _the_content_ filters, correct?
I would just merge your workaround into the plugin, but I have a feeling that the nesting might cause all sorts of trouble with other plugins down the road as well.  Do you have any other ideas how to solve this?

**Comment by Genyus** [comment]
Having slept on it, I think the onus here lies with Thrive, not yourselves. In my scenario, TGF calls _the_content_ on an empty string, but Thrive then (unexpectedly) injects the markup from the editor which contains the privacy tools shortcode, which then gets processed by the _do_shortcode_ filter, and round we go.

So the real issue here is that markup coming from Thrive, which shouldn't be rendered in this instance. They already have a compatibility file that addresses a number of conflicts with other extensions, some of which have very similar solutions as to what would be necessary here. I will report this to their team also.

However, if you wanted to protect against similar potential conflicts with other page builders or plugins, then I think one way would be to test if the shortcode is being processed by _the_content_, e.g. `if ( doing_filter( 'the_content' ) ) { ... }`. In this instance, that should prevent the infinite recursion and avoid the 500 error, but you would still end up with the Thrive-generated content being rendered where it shouldn't.

**Comment by Genyus** [comment]
A second preventative measure that comes to mind would be to simply eliminate the additional call to _the_content_ entirely. I haven't dug into your code thoroughly enough to understand what consequences or challenges that might present, but it seems that Thrive make the implicit assumption that _the_content_ would only be called once on the page. So the trick here would be to get your content processed before or during the default execution.

**Comment by indrek-k** [comment]
Thanks for the feedback! While this might be an issue with Thrive, it's easier to solve this myself rather than wait for them to react. I'm considering just removing the filter from the textarea, it's probably the easiest solution.

I have a feeling quite a few unsolved support requests are due to this bug. It's really awesome that you tracked it down!

**Comment by Genyus** [comment]
Ah, fair enough. I do see how there could be potential for conflicts stemming from that call. Took me a while to figure it out, but if it assists anyone else, then I'm glad I could help!

**Comment by indrek-k** [comment]
Replaced the_content filter with a simple wpautop() call to handle line breaks properly. Will push to WP repo soon. Thanks again for your help, this most likely just saved me and a lot of other people a ton of headache.
