### ISSUE TITLE
Translate bugs -  untranslatable texts

### ISSUE THREAD

**Issue by trueqap** [codelight-eu/gdpr-framework#9]
'Add consent type' button.

`<input data-repeater-create class="button button-primary" type="button" value="Add consent type"/>`

consent.php line 78

**Comment by trueqap** [comment]
Need help text: 

    Need help? Take a look at our <a href="<?= gdpr('helpers')->docs('wordpress-site-owners-guide-to-gdpr/'); ?>" target="_blank">documentation</a>.

help.php

**Comment by trueqap** [comment]
See the list of contacts here text:

`      echo "<a href='https://codelight.eu/wordpress-gdpr-framework/knowledge-base/do-i-need-to-appoint-an-eu-based-representative/' target='_blank'>";
        echo 'See the <a href="http://ec.europa.eu/justice/data-protection/article-29/structure/data-protection-authorities/index_en.htm" target="_blank">list of contacts here</a>';
        echo "</a>";`

AdminTabPrivayPolicy.php

**Comment by trueqap** [comment]
I have appointed a Data Protection Officer text
 on privacy-policy tab

**Comment by trueqap** [comment]
`<p>
    The GDPR Framework has not been set up yet. Would you like to do that? <br>
    Our setup wizard will guide you through the process. <br>
    You can also configure the plugin manually by going to <a href="<?= gdpr('helpers')->getAdminUrl(); ?>">Tools > Privacy</a>.
</p>`

welcome-notice.php

**Comment by trueqap** [comment]
And the setup wizart completely :)

**Comment by indrek-k** [comment]
Thanks so much for pointing these out. The others have been fixed, apart from the wizard and wizard-related notifications. This would be a rather big undertaking and I don't have time for this immediately. 

If someone has time to help with this, that would be really appreciated!

**Comment by trueqap** [comment]
I have time :) I
